services:
  db:
    container_name: solrunners-site-db
    image: couchdb:latest
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=dikkedraak
    ports:
      - "5984:5984"    
  server:
    container_name: solrunners-site-server
    depends_on: [db]
    build: .
    environment:
      - COUCHDB_URL=http://solrunners-site-db:5984
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=dikkedraak
    ports:
      - "8000:8000"    



