name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - run: rustup toolchain install stable --profile minimal    
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "cargo"
        shared-key: "build-cache"        
        cache-on-failure: "true"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "cargo"
        shared-key: "build-cache"        
    - run: cargo test
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "cargo"
        shared-key: "build-cache"        
    - run: cargo clippy
          
          
          
          
          
          

    
  
 
